# Generated by Django 4.2.1 on 2023-05-26 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcha_posteo', models.DateField(auto_now_add=True)),
                ('fcha_modificacion', models.DateField(auto_now=True)),
                ('marca', models.CharField(max_length=32)),
                ('modelo', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('descripcion', models.CharField(max_length=1500)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefono', models.IntegerField()),
                ('patente', models.CharField(blank=True, max_length=7)),
                ('precio', models.IntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
