# Generated by Django 4.2.1 on 2023-05-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_vehiculos'),
        ),
    ]
