# Generated by Django 4.2.1 on 2023-05-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0004_posteo_kilometros'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='reserva',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posteo',
            name='user_reserva',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
